services:
  backend:
    build: ./Lunaris
    container_name: lunaris_backend
    expose:
      - "8000"
    volumes:
      - ./Lunaris:/app
    environment:
      - ANILIST_API_URL=https://graphql.anilist.co
      - DATABASE_URL=sqlite:///./soluna.db
    restart: always

  frontend:
    build: ./Solaris
    container_name: solaris_frontend
    expose:
      - "80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=https://cc.tokihato.com/api
    restart: always

  caddy:
    image: caddy:2-alpine
    container_name: soluna_caddy
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  caddy_data:
  caddy_config:
